version: 3.1.1.{build}

os: Visual Studio 2017

skip_tags: true

branches:
  except:
    - configdata
    - gh-pages

environment:
  matrix:
  - IdeVersion: VS2017
  SKIP_PAUSE: TRUE
  ARCHIVE_WITH_PDB: TRUE
  ARTIFACT_SIGNING_ENABLED: TRUE

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  # enable MSBuild parallel builds
  parallel: true
  # MSBuild verbosity level
  verbosity: minimal

cache:
  #- packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - packages\WiX.3.11.0 -> Setup\packages.config

install:
- cmd: git submodule update --init --recursive
- cmd: echo /logger:"%ProgramFiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll">> Directory.Build.rsp
- cmd: |-
    cd Setup
    C:\\Python35\\python set_version_to.py -v %APPVEYOR_BUILD_VERSION% -t %APPVEYOR_BUILD_VERSION%
    cd ..

# to run your custom scripts instead of automatic MSBuild
build_script:
- ps: |
    Write-Output "Platform: $env:IdeVersion"
    # for release branches mark the repo as clean
    if (!$env:APPVEYOR_PULL_REQUEST_TITLE) {
      & Build\Mark-RepoClean.ps1
    }
    # build
    & Setup\Build.cmd
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

# to run your custom scripts instead of automatic tests
#test: off
test_script:
- ps: |
    Write-Host "Ignore the tests and codecov util we figure out how to use OpenCover"
    # & .\Build\Run-Tests.ps1

# scripts to run after tests
after_test:
- ps: |
    Write-Host "Preparing build artifacts..."
    & .\Build\Prepare-Artifacts.ps1
    # do not sign artifacts for non-release branches, publish dev builds
    if ($env:APPVEYOR_PULL_REQUEST_TITLE -eq $true) {
        Write-Host "[INFO]: Do not sign non-release branches"
        Get-ChildItem GitExtensions-Portable-*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
        Get-ChildItem GitExtensionsVSIX.vsix | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
        Exit-AppVeyorBuild
        return
    }

artifacts:
  # upload the generated portable archive only
  - path: 'combined.*-unsigned.zip'
  - path: GitExtensions-pdbs-*.zip

deploy:
  release: $(APPVEYOR_BUILD_VERSION)
  description: ""
  provider: GitHub
  auth_token:
    secure: rXu9qtKcQQGqMciH1aloVBxwqYuiqrtLd04CYPey4hKMu2AN9Mtl4j+98dPP+V1r
  artifact: Setup/GitExtensions-$(APPVEYOR_BUILD_VERSION).msi
  draft: false
  prerelease: true
  APPVEYOR_REPO_TAG: false
  on:
    branch: /release\/.*/

